on:
  workflow_dispatch:
jobs:
  create-branch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: |
          gh pr list --json "headRefName,statusCheckRollup"  --repo "wordpress/gutenberg" --search "is:open is:pr 'Mobile Release'in:title"
